services:
  go:
    volumes:
      - type: bind
        source: ./
        target: /go/app
    command: >
      bash -c '
        protoc ./schema/*.proto --go_out=./api/ --go-grpc_out=./api/
      '
    build:
      dockerfile: ./docker/go/Dockerfile
  node:
    volumes:
      - type: bind
        source: ./
        target: /node/app
    command: >
      bash -c '
        cd schema
        grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../api/limiterpb/ --grpc_out=grpc_js:../api/limiterpb/ limiter.proto
        grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../api/serverpb/ --grpc_out=grpc_js:../api/serverpb/ server.proto
      grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../api/limiterpb/testpb/ --grpc_out=grpc_js:../api/limiterpb/testpb/ test.proto
      '
    build:
      dockerfile: ./docker/node/Dockerfile
    platform: "linux/amd64"

