// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: schema/limiter.proto

package limiterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain                  string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Key                     string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	MaxHitsPerWindow        uint32 `protobuf:"varint,3,opt,name=max_hits_per_window,json=maxHitsPerWindow,proto3" json:"max_hits_per_window,omitempty"`
	WindowExpirationSeconds uint32 `protobuf:"varint,4,opt,name=window_expiration_seconds,json=windowExpirationSeconds,proto3" json:"window_expiration_seconds,omitempty"`
}

func (x *LimitRequest) Reset() {
	*x = LimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_limiter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitRequest) ProtoMessage() {}

func (x *LimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_limiter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitRequest.ProtoReflect.Descriptor instead.
func (*LimitRequest) Descriptor() ([]byte, []int) {
	return file_schema_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *LimitRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LimitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LimitRequest) GetMaxHitsPerWindow() uint32 {
	if x != nil {
		return x.MaxHitsPerWindow
	}
	return 0
}

func (x *LimitRequest) GetWindowExpirationSeconds() uint32 {
	if x != nil {
		return x.WindowExpirationSeconds
	}
	return 0
}

type LimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit bool `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *LimitResponse) Reset() {
	*x = LimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_limiter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitResponse) ProtoMessage() {}

func (x *LimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_limiter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitResponse.ProtoReflect.Descriptor instead.
func (*LimitResponse) Descriptor() ([]byte, []int) {
	return file_schema_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *LimitResponse) GetLimit() bool {
	if x != nil {
		return x.Limit
	}
	return false
}

type LimitStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LimitStatusRequest) Reset() {
	*x = LimitStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_limiter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitStatusRequest) ProtoMessage() {}

func (x *LimitStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_limiter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitStatusRequest.ProtoReflect.Descriptor instead.
func (*LimitStatusRequest) Descriptor() ([]byte, []int) {
	return file_schema_limiter_proto_rawDescGZIP(), []int{2}
}

type LimitStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total      uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Error      uint64 `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	LimitTrue  uint64 `protobuf:"varint,3,opt,name=limit_true,json=limitTrue,proto3" json:"limit_true,omitempty"`
	LimitFalse uint64 `protobuf:"varint,4,opt,name=limit_false,json=limitFalse,proto3" json:"limit_false,omitempty"`
}

func (x *LimitStatusResponse) Reset() {
	*x = LimitStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_limiter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitStatusResponse) ProtoMessage() {}

func (x *LimitStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_limiter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitStatusResponse.ProtoReflect.Descriptor instead.
func (*LimitStatusResponse) Descriptor() ([]byte, []int) {
	return file_schema_limiter_proto_rawDescGZIP(), []int{3}
}

func (x *LimitStatusResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LimitStatusResponse) GetError() uint64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *LimitStatusResponse) GetLimitTrue() uint64 {
	if x != nil {
		return x.LimitTrue
	}
	return 0
}

func (x *LimitStatusResponse) GetLimitFalse() uint64 {
	if x != nil {
		return x.LimitFalse
	}
	return 0
}

var File_schema_limiter_proto protoreflect.FileDescriptor

var file_schema_limiter_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x22,
	0xa3, 0x01, 0x0a, 0x0c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x13, 0x6d, 0x61,
	0x78, 0x5f, 0x68, 0x69, 0x74, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6d, 0x61, 0x78, 0x48, 0x69, 0x74, 0x73,
	0x50, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x3a, 0x0a, 0x19, 0x77, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x17, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x25, 0x0a, 0x0d, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x14, 0x0a, 0x12,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f,
	0x74, 0x72, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x54, 0x72, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x66,
	0x61, 0x6c, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x46, 0x61, 0x6c, 0x73, 0x65, 0x32, 0x8b, 0x01, 0x0a, 0x07, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x65, 0x72, 0x12, 0x36, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x15, 0x2e, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72,
	0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_limiter_proto_rawDescOnce sync.Once
	file_schema_limiter_proto_rawDescData = file_schema_limiter_proto_rawDesc
)

func file_schema_limiter_proto_rawDescGZIP() []byte {
	file_schema_limiter_proto_rawDescOnce.Do(func() {
		file_schema_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_limiter_proto_rawDescData)
	})
	return file_schema_limiter_proto_rawDescData
}

var file_schema_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_schema_limiter_proto_goTypes = []interface{}{
	(*LimitRequest)(nil),        // 0: limiter.LimitRequest
	(*LimitResponse)(nil),       // 1: limiter.LimitResponse
	(*LimitStatusRequest)(nil),  // 2: limiter.LimitStatusRequest
	(*LimitStatusResponse)(nil), // 3: limiter.LimitStatusResponse
}
var file_schema_limiter_proto_depIdxs = []int32{
	0, // 0: limiter.Limiter.Limit:input_type -> limiter.LimitRequest
	2, // 1: limiter.Limiter.LimitStatus:input_type -> limiter.LimitStatusRequest
	1, // 2: limiter.Limiter.Limit:output_type -> limiter.LimitResponse
	3, // 3: limiter.Limiter.LimitStatus:output_type -> limiter.LimitStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_limiter_proto_init() }
func file_schema_limiter_proto_init() {
	if File_schema_limiter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_limiter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_limiter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_limiter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_limiter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_limiter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_limiter_proto_goTypes,
		DependencyIndexes: file_schema_limiter_proto_depIdxs,
		MessageInfos:      file_schema_limiter_proto_msgTypes,
	}.Build()
	File_schema_limiter_proto = out.File
	file_schema_limiter_proto_rawDesc = nil
	file_schema_limiter_proto_goTypes = nil
	file_schema_limiter_proto_depIdxs = nil
}
